### ISSUE TITLE
The inference time

### ISSUE THREAD

**Issue by TeleeMa** [Vision-CAIR/ChatCaptioner#1]
Thank you for your great work!

I am currently having trouble receiving any response from ChatGPT during the caption.ipynb inference process, although I am able to use ChatGPT through a web browser. Could you please let me know the expected time for each chat process during inference, and if using ChatGPT Plus would help to accelerate this process.

<img width="1378" alt="Screenshot 2023-03-29 at 3 59 21 PM" src="https://user-images.githubusercontent.com/33897627/228467883-8a2bb7c4-8f2e-4fc1-9629-85805197f83f.png">

Thank you for your assistance!

**Comment by TsuTikgiau** [comment]
Hello TeleeMa, the whole conversation is usually finished in 10 seconds, and each round takes about 1 second. If the code works normally, you should directly see the printout questions and answers in 1 second. In your case, I guess there is some issue in the connection with OpenAI server. The function that submits the request to OpenAI server is [call_chatgpt in chatcaptioner/chat.py](https://github.com/Vision-CAIR/ChatCaptioner/blob/main/chatcaptioner/chat.py#L119). You can see that this function has a retry decorator at L118. This is used to automatically resubmit the request to OpenAI server when the previous trials do not success. You can commit out this decorator, so the code will not resubmit, instead raise an error to show you what's wrong.

**Comment by TeleeMa** [comment]
Hi TsuTikgiau，

Thank you for your reply. It turns out that there was indeed an issue with the connection to the OpenAI server.
