### ISSUE TITLE
视频字幕任务中所需要的caption.txt的作用是什么呢

### ISSUE THREAD

**Issue by NEFUJoeyChen** [Vision-CAIR/ChatCaptioner#2]
或者说有没有如何使用个人上传视频完成字幕生成的详细操作指引呢？如果能像图像字幕那样开发gradio web页面最好不过了，再次感谢开发者的工作

**Comment by junchen14** [comment]
视频生成字幕只需要视频视觉信息。并不需要任何caption.txt
目前并没有计划对video ChatCaptioner 项目 开发gradio web 页面

**Comment by NEFUJoeyChen** [comment]
> https://github.com/Vision-CAIR/ChatCaptioner/blob/e4c63eeedaa40fceac52ef6a555a9ae608feaa81/Video_ChatCaptioner/generate_caption_msvd.py#L46

谢谢您的回复，可是看到脚本这里需要video caption 对  这里不是很理解您说不需要任何caption.txt信息

`Traceback (most recent call last):
  File "/home/chenjh/chenjh/ChatCaptioner/Video_ChatCaptioner/generate_caption_msvd.py", line 49, in <module>
    with open(CAPTION_FILE,"r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'msvd_data/caption.txt'
`

**Comment by junchen14** [comment]
这里只是整理msvd 的 ground-truth image caption  信息，方便video ChatCaptioner 生成的结果和ground-truth 进行对比
